# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop

pr:
  branches:
    include:
    - develop

pool:
  vmImage: 'windows-2019'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: PowerShell@2
  displayName: Install gitversion.tool
  inputs:
    targetType: inline
    script: dotnet tool install --tool-path .. gitversion.tool
    pwsh: true

- task: PowerShell@2
  displayName: Set SemVer from git history
  inputs:
    targetType: inline
    script: ../dotnet-gitversion /output buildserver
    pwsh: true

- task: SonarCloudPrepare@1
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Prepare SonarCloud analysis"
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mgroupntua'
    scannerMode: 'MSBuild'
    projectKey: 'MSolve.Constitutive'
    extraProperties: 'sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/coverage/coverage.opencover.xml'

- task: DotNetCoreCLI@2
  name: dotnetRestore
  displayName: "Restore nugets"
  inputs:
    command: 'restore'
    verbosityRestore: 'Normal'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'

- task: DotNetCoreCLI@2
  name: dotnetBuild
  displayName: "Build projects"
  inputs:
    command: 'build'
    arguments: '--no-restore --nologo --configuration $(buildConfiguration) /p:AssemblyVersion=$(GitVersion.AssemblySemVer) /p:Version=$(GitVersion.SemVer) /p:SourceLinkCreate=true'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.AssemblySemVer'

- task: DotNetCoreCLI@2
  enabled: true
  displayName: Run tests (develop)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    publishTestResults: true

- task: PowerShell@2
  enabled: true
  displayName: Clone MSolve.Tests
  inputs:
    targetType: inline
    script: mkdir integrationTests ; cd integrationTests ; git clone https://github.com/mgroupntua/MSolve.Tests.git;
    pwsh: true

- task: CopyFiles@2
  enabled: true
  displayName: Copy Constitutive project on MSolve.Tests
  inputs:
    sourceFolder: 'D:\a\1\s'
    Contents: |
      **/*
      !integrationTests/**/*
    targetFolder: 'D:\a\1\s\integrationTests\Constitutive'
    cleanTargetFolder: true # Optional

- task: PowerShell@2
  enabled: true
  displayName: Clone FEM in Integration Tests
  inputs:
    targetType: inline
    script: cd integrationTests ; git clone https://github.com/mgroupntua/FEM.git ; dir ;
    pwsh: true

- script: dotnet remove D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.Structural\MGroup.FEM.Structural.csproj package MGroup.Constitutive.Structural
  displayName: Remove Package Constitutive.Structural from FEM.Structural
  enabled: true

- script: dotnet add D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.Structural\MGroup.FEM.Structural.csproj reference D:\a\1\s\integrationTests\Constitutive\src\MGroup.Constitutive.Structural\MGroup.Constitutive.Structural.csproj
  displayName: Add project ref Constitutive.Structural to FEM.Structural
  enabled: true

- script: dotnet remove D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.Thermal\MGroup.FEM.Thermal.csproj package MGroup.Constitutive.Thermal
  displayName: Remove Package Constitutive.Thermal from FEM.Thermal
  enabled: true

- script: dotnet add D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.Thermal\MGroup.FEM.Thermal.csproj reference D:\a\1\s\integrationTests\Constitutive\src\MGroup.Constitutive.Thermal\MGroup.Constitutive.Thermal.csproj
  displayName: Add project ref Constitutive.Thermal to FEM.Thermal
  enabled: true

- script: dotnet remove D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.ConvectionDiffusion\MGroup.FEM.ConvectionDiffusion.csproj package MGroup.Constitutive.ConvectionDiffusion
  displayName: Remove Package Constitutive.ConvectionDiffusion from FEM.ConvectionDiffusion
  enabled: true

- script: dotnet add D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.ConvectionDiffusion\MGroup.FEM.ConvectionDiffusion.csproj reference D:\a\1\s\integrationTests\Constitutive\src\MGroup.Constitutive.ConvectionDiffusion\MGroup.Constitutive.ConvectionDiffusion.csproj
  displayName: Add project ref Constitutive.ConvectionDiffusion to FEM.ConvectionDiffusion
  enabled: true

- script: dotnet remove D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.Structural.Tests\MGroup.FEM.Structural.Tests.csproj package MGroup.FEM.Structural
  displayName: Remove Package FEM.Structural from MSolve.Tests
  enabled: true

- script: dotnet add D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.Structural.Tests\MGroup.FEM.Structural.Tests.csproj reference D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.Structural\MGroup.FEM.Structural.csproj
  displayName: Add project ref FEM.Structural to MSolve.Tests
  enabled: true

- script: dotnet remove D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.Thermal.Tests\MGroup.FEM.Thermal.Tests.csproj package MGroup.FEM.Thermal
  displayName: Remove Package FEM.Thermal from MSolve.Tests
  enabled: true

- script: dotnet add D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.Thermal.Tests\MGroup.FEM.Thermal.Tests.csproj reference D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.Thermal\MGroup.FEM.Thermal.csproj
  displayName: Add project ref FEM.Thermal to MSolve.Tests
  enabled: true

- script: dotnet remove D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.ConvectionDiffusion.Tests\MGroup.FEM.ConvectionDiffusion.Tests.csproj package MGroup.FEM.ConvectionDiffusion
  displayName: Remove Package FEM.ConvectionDiffusion from MSolve.Tests
  enabled: true

- script: dotnet add D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.ConvectionDiffusion.Tests\MGroup.FEM.ConvectionDiffusion.Tests.csproj reference D:\a\1\s\integrationTests\FEM\src\MGroup.FEM.ConvectionDiffusion\MGroup.FEM.ConvectionDiffusion.csproj
  displayName: Add project ref FEM.ConvectionDiffusion to MSolve.Tests
  enabled: true

- task: DotNetCoreCLI@2
  enabled: true
  displayName: Runs MSolve.Tests (master)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    command: 'test'
    projects: |
      D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.Structural.Tests\MGroup.FEM.Structural.Tests.csproj
      D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.Thermal.Tests\MGroup.FEM.Thermal.Tests.csproj
      D:\a\1\s\integrationTests\MSolve.Tests\tests\MGroup.FEM.ConvectionDiffusion.Tests\MGroup.FEM.ConvectionDiffusion.Tests.csproj
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    publishTestResults: true

- task: PublishSymbols@2
  displayName: "Publish symbols to Azure Devops artifacts"
  inputs:
    DetailedLog: true
    SearchPattern: '**/bin/**/*.pdb'
    IndexSources: false
    SymbolServerType: 'TeamServices'

- task: SonarCloudAnalyze@1
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Perform SonarCloud Analysis"

- task: SonarCloudPublish@1
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: 'Publish Quality Gate results'
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@1
  enabled: false
  displayName: 'Publish code coverage results'
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)/coverage/Cobertura/Cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/coverage/Cobertura
    codecoverageTool: cobertura

- task: DeleteFiles@1
  displayName: 'Remove integration tests dir'
  inputs:
    contents: |
      **/integrationTests/*

- task: DotNetCoreCLI@2
  name: dotnetPack
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Package new nugets"
  inputs:
    command: 'pack'
    arguments: '--nologo --no-restore'
    nobuild: true
#    includesymbols: true
#    includesource: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.SemVer'
    verbosityPack: 'Normal'

- task: CopyFiles@2
  enabled: false
  displayName: "Copy everything in artifacts staging directory"
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  name: publishToFeed
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Publish to pipeline artifacts"
  inputs:
    ArtifactName: 'drop'

- task: DotNetCoreCLI@2
  name: dotnetPushNugetPublic
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Push nugets to public feed"
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    verbosityPack: 'Minimal'
    feedPublish: 'MSolve/MGroup'

- task: DotNetCoreCLI@2
  enabled: false
  condition: ne(variables['Build.Reason'], 'PullRequest')
  name: dotnetPushSymbolPublic
  displayName: "Publish symbol nugets"
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.snupkg'
    feedPublish: 'MSolve/MGroup'
